name: 🧪 Check

on:
  push:
    branches:
      - master
      - dev
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: 🧪 Check
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Set up the toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-unknown-linux-gnu"
          components: "clippy"

      - name: ⚡️ Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: ✨ Set up B(inary)Install
        uses: cargo-bins/cargo-binstall@main

      - name: ✨ Set up Cross
        run: cargo binstall cross

      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test
        run: cross test -- --include-ignored
        env:
          CROSS_CONTAINER_OPTS: "--network=host"

      - name: 💬 Clippy
        run: cross clippy --test
        if: github.event_name == 'pull_request'
        continue-on-error: true
