name: ✨ Publish
run-name: 🔖 Publish ${{ github.ref_name }}

on:
  release:
    types: [ "published" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ✨ Publish
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: ⚡️ Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: ⚡️ Set up Shared Compilation Cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: 📦 Publish the crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
