name: ✨ Publish
run-name: 🔖 Publish ${{ github.ref_name }}

on:
  release:
    types: [ "published" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  crate:
    name: ✨ Publish to crates.io
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 📦 Publish the crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  windows-build:
    name: 🪟 Build for Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 🏗️ Build
        run: cargo build --release

      - name: 📤 Upload asset
        run: gh release upload '$GITHUB_REF' target/release/mrktpltsbot.exe
        env:
          GH_TOKEN: ${{ github.token }}
