name: ✨ Publish
run-name: 🔖 Publish ${{ github.ref_name }}

on:
  release:
    types: [ "published" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ✨ Publish
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: ⚡️ Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: ⚡️ Set up Shared Compilation Cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: 🏗️ Cargo Build
        run: cargo build --release

      - name: 📤 Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/mrktpltsbot
          asset_name: mrktpltsbot.aarch64-apple-darwin
          asset_content_type: application/octet-stream
